---
title: Laat GameObjects verschijnen of verdwijnen met SetActive
hero_image: images/banner.png
description: Laat GameObjects verschijnen of verdwijnen met SetActive
version: 4
listed: false
copyedit: false
last_tested: "2021-11-22"
steps:
  - title: Laat GameObjects verschijnen of verdwijnen met SetActive
