title: Make GameObjects appear or disappear using SetActive
hero_image: images/banner.png
description: Make GameObjects appear or disappear using SetActive
version: 4
listed: false
copyedit: false
last_tested: "2021-11-22"
steps:
  - 
    title: Make GameObjects appear or disappear using SetActive
